name: PR CI

on:
  push:
  pull_request:

jobs:
  fail:
    runs-on: ubuntu-latest
    if: github.repository != 'assignUser/indirect-ci'
    steps:
      - run: exit 1
  success:
    runs-on: ubuntu-latest
    if: github.repository != 'assignUser/indirect-ci'
    steps:
      - run: exit 0
